server:
  port: 10050
spring:
  application:
    name: jushi-oss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: localhost
  data:
    mongodb:
      uri: mongodb://localhost:27017/jushi

logging:
  level:
    # root: debug
    org.springframework.data.mongodb.core: DEBUG

